--EJERCICIO 6--
CREATE OR REPLACE PROCEDURE p_FECHAVIAJE IS
    v_FECHA VIAJES.FECHA%TYPE;
    CURSOR cVIAJES IS
    SELECT VIAJES.FECHA INTO v_FECHA FROM VIAJES, CONDUCTOR 
    WHERE VIAJES.DNI_CONDUCTOR = CONDUCTOR.DNI 
    AND CONDUCTOR.NUM_EMPLEADO = (SELECT MIN(NUM_EMPLEADO) FROM CONDUCTOR);
    v_FECHAVIAJE cVIAJES%ROWTYPE;
BEGIN
        DBMS_OUTPUT.PUT_LINE('Fecha: '||v_FECHA);
END;

CALL p_FECHAVIAJE();