--EJERCICIO 10--
CREATE OR REPLACE FUNCTION f_MAYOR(i_NUMERO1 NUMBER,i_NUMERO2 NUMBER, i_NUMERO3 NUMBER) RETURN NUMBER IS 
    v_NUMERO1 NUMBER:= i_NUMERO1;
    v_NUMERO2 NUMBER:= i_NUMERO2;
    v_NUMERO3 NUMBER:= i_NUMERO3;
BEGIN
    IF v_NUMERO1>v_NUMERO2 THEN
        IF v_NUMERO1>v_NUMERO3 THEN
        return v_NUMERO1;
        ELSE
            return v_NUMERO3;
        END IF;
    ELSIF v_NUMERO2>v_NUMERO3 THEN
        return v_NUMERO2;
    ELSE
        return v_NUMERO3;
    END IF;
END;

SELECT f_MAYOR(9,10,12) from dual;