--EJERCICIO 3--
CREATE OR REPLACE PROCEDURE p_CADENA(i_CADENA VARCHAR2) IS
    v_CADENANUEVA VARCHAR2(30);
    v_CADENA VARCHAR2(30) := i_CADENA;
BEGIN
    FOR i IN REVERSE 1..LENGTH(v_CADENA) LOOP
        v_CADENANUEVA := v_CADENANUEVA || SUBSTR(v_CADENA, i, 1);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE(v_CADENANUEVA);
EXCEPTION
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERROR');
END;

CALL p_CADENA('Hola Mundo');