--EJERCICIO 2--
CREATE OR REPLACE FUNCTION f_DIVISION(i_NUMEOR1 NUMBER, i_NUMERO2 NUMBER) RETURN NUMBER IS
    v_NUMERO1 NUMBER(4) := i_NUMEOR1;
    v_NUMERO2 NUMBER(4) := i_NUMERO2;
    v_RESULTADO NUMBER(2);
BEGIN
    v_RESULTADO := v_NUMERO1 / v_NUMERO2;
    RETURN v_RESULTADO;
EXCEPTION
    WHEN ZERO_DIVIDE THEN v_RESULTADO := -1;
    RETURN v_RESULTADO;
END;
--COMPROVACIONES--
SELECT f_DIVISION(10, 5) FROM DUAL;
SELECT f_DIVISION(2, 0) FROM DUAL;