--EJERCICIO 9--
CREATE OR REPLACE FUNCTION f_AREACIRCULO(i_RADIOCIRCULO IN NUMBER) RETURN NUMBER IS
    v_RADIOCIRCULO NUMBER:=i_RADIOCIRCULO;
    v_AREACIRCULO NUMBER;
BEGIN
    v_AREACIRCULO :=  (3.14 * POWER(v_RADIOCIRCULO, 2));
    RETURN v_AREACIRCULO;
END;

SELECT f_AREACIRCULO(3.3) FROM DUAL;