--EJERCICIO 12--
CREATE OR REPLACE PROCEDURE p_CAMBIOFECHA (i_NOMBREDEPARTAMENTO IN VARCHAR) IS

    v_NOMBREDEPARTAMENTO DEPARTAMENTO.NOMBRE%TYPE:=i_NOMBREDEPARTAMENTO;
    v_FECHA_ALTA DATOSPERSONALES.FECHA_ALTA%TYPE;
    v_FECHAHOY DATE;
    v_OK VARCHAR2(2):='OK';

BEGIN
    --PASO--
    SELECT MIN(FECHA_ALTA) INTO v_FECHA_ALTA FROM DATOSPERSONALES,DEPARTAMENTO,EMPLEADOS 
    WHERE  DEPARTAMENTO.ID_DEPARTAMENTO = EMPLEADOS.ID_DEPARTAMENTO
    AND EMPLEADOS.ID_EMPLEADO = DATOSPERSONALES.CLAVE_EMPLEADO
    AND DEPARTAMENTO.NOMBRE=v_NOMBREDEPARTAMENTO;
    --PASO--
    SELECT SYSDATE INTO v_FECHAHOY FROM DUAL;
    --PASO--
    UPDATE DATOSPERSONALES SET FECHA_ALTA=v_FECHAHOY WHERE FECHA_ALTA=v_FECHA_ALTA;
    --PASO--
    DBMS_OUTPUT.PUT_LINE(v_OK);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO SE HA ENCONTRADO EL NOMBRE DEL DEPARTAMENTO INDICADO');
END;

CALL p_CAMBIOFECHA('Manufactura');
--PASO--
SELECT FECHA_ALTA FROM DATOSPERSONALES ORDER BY FECHA_ALTA DESC;