--EJERCICIO 4--
CREATE OR REPLACE PROCEDURE p_PERSONAL IS
    CURSOR  cEMPLEADO IS
    SELECT EMPLEADOS.NOMBRE,DATOSPERSONALES.FECHA_ALTA 
    FROM DATOSPERSONALES,EMPLEADOS 
    WHERE DATOSPERSONALES.CLAVE_EMPLEADO=EMPLEADOS.ID_EMPLEADO;

    TYPE rEMPLEADO IS RECORD(
        v_NOMBRE EMPLEADOS.NOMBRE%TYPE,
        v_FECHA_ALTA DATOSPERSONALES.FECHA_ALTA%TYPE
    );
    v_EMPLEADO rEMPLEADO;

BEGIN
    OPEN cEMPLEADO;
    FETCH cEMPLEADO INTO v_EMPLEADO;
    WHILE cEMPLEADO%FOUND LOOP
        DBMS_OUTPUT.PUT_LINE('Nombre: ' || v_EMPLEADO.NOMBRE || ' | ' || 'Fecha de alta: '|| v_EMPLEADO.FECHA_ALTA);
        FETCH cEMPLEADO INTO v_EMPLEADO;
    END LOOP;
    CLOSE cEMPLEADO;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Excepción en el código');
END;

CALL p_PERSONAL();