--EJERCICIO 11--
CREATE OR REPLACE FUNCTION f_APELLIDOSCONDUCTOR(i_DNICONDUCTOR VARCHAR)RETURN VARCHAR2 IS
    v_DNICONDUCTOR CONDUCTOR.DNI%TYPE := i_DNICONDUCTOR;
    v_PRAPELLIDO CONDUCTOR.PRAPELLIDO%TYPE;
    v_SGAPELLIDO CONDUCTOR.SGAPELLIDO%TYPE;
    v_APELLIDOS VARCHAR2(30);
BEGIN
    SELECT PRAPELLIDO, SGAPELLIDO INTO v_PRAPELLIDO, v_SGAPELLIDO FROM CONDUCTOR WHERE DNI = v_DNICONDUCTOR;
    v_APELLIDOS:=(v_PRAPELLIDO||' '||v_SGAPELLIDO);
    RETURN vAPELLIDOS;
END;

SELECT f_APELLIDOSCONDUCTOR('') FROM DUAL;
