--EJERCICIO 8--
CREATE OR REPLACE PROCEDURE p_DIASEMANA(i_DIASEMANA in NUMBER) IS
    v_DIASEMANA NUMBER := i_DIASEMANA;
    v_DIATEXTO VARCHAR2(10);
    DIAMALO EXCEPTION;
BEGIN
    IF v_DIASEMANA>7 OR v_DIASEMANA<1 THEN
        RAISE DIAMALO;
    ELSE
        CASE v_DIASEMANA
            WHEN 1 THEN v_DIATEXTO := 'Lunes';
            WHEN 2 THEN v_DIATEXTO := 'Martes';
            WHEN 3 THEN v_DIATEXTO := 'Miercoles';
            WHEN 4 THEN v_DIATEXTO := 'Jueves';
            When 5 THEN v_DIATEXTO := 'Vienes';
            WHEN 6 THEN v_DIATEXTO := 'Sabado';
            WHEN 7 THEN v_DIATEXTO := 'Domingo'; 
        END CASE;
    END IF;
    DBMS_OUTPUT.PUT_LINE(v_DIATEXTO);
EXCEPTION
    WHEN DIAMALO THEN
    DBMS_OUTPUT.PUT_LINE('EL DIA INTRODUCIDO NO ES ACORDE');
END;

CALL p_DIASEMANA(8);