SET SERVEROUTPUT ON;
--EJERCICIO 1--
CREATE OR REPLACE PROCEDURE p_VARIABLE IS
    v_Variable NUMBER(1) := 5;
BEGIN
    DBMS_OUTPUT.PUT_LINE('LA VARIABLE TOMA EL VALOR DE: '||v_Variable);
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR');
END;

CALL p_VARIABLE();